name: lifeguard
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_search_bar: ^3.0.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  responsive_builder: ^0.7.1
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true
fonts:
  - family: Nunito
    fonts:
      - asset: build/flutter_assets/fonts/Nunito-Regular.ttf
      - asset: build/flutter_assets/fonts/Nunito-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: "lifeguard_logo"
  ios: true
  image_path: "assets/lifeguard_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/lifeguard_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/lifeguard_logo.png"
