name: lifeguard
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_search_bar: ^3.0.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  responsive_builder: ^0.7.1
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  image_picker: ^0.8.4+3
  file_picker: ^5.2.7
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true
fonts:
  - family: Nunito
    fonts:
      - asset: build/flutter_assets/fonts/Nunito-Regular.ttf
      - asset: build/flutter_assets/fonts/Nunito-Bold.ttf
        weight: 700

