name: Deploy Flutter Web

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Check if build/web exists
        run: |
          if [ ! -d "build/web" ]; then
            echo "Directory build/web does not exist!"
            exit 1
          fi

      - name: Deploy to Server via Rsync
        uses: burnett01/rsync-deployments@5.2.3
        with:
          switches: -avzr --delete
          path: build/web/         
          remote_path: /var/www/html/  
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }} 
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Set permissions and restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html 
            sudo chmod -R 755 /var/www/html            
            sudo systemctl restart nginx            
